KERNEL_ARCH_CFLAGS =
KERNEL_ARCH_LDFLAGS =
KERNEL_ARCH_LIBS =

KERNEL_ARCH_OBJS = $(ARCHDIR)/boot.o $(ARCHDIR)/tty.o $(ARCHDIR)/crti.o \
		   $(ARCHDIR)/crtbegin.o $(ARCHDIR)/crtend.o $(ARCHDIR)/crtn.o
